# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'X:\UNote\src\ui\preferences_gui.ui',
# licensing of 'X:\UNote\src\ui\preferences_gui.ui' applies.
#
# Created: Sun Oct 20 20:47:22 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(838, 1018)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelAppearance = QtWidgets.QLabel(PreferencesDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelAppearance.setFont(font)
        self.labelAppearance.setObjectName("labelAppearance")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelAppearance)
        self.groupBoxThemeSwitch = QtWidgets.QGroupBox(PreferencesDialog)
        self.groupBoxThemeSwitch.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBoxThemeSwitch.setTitle("")
        self.groupBoxThemeSwitch.setObjectName("groupBoxThemeSwitch")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBoxThemeSwitch)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutThemeSwitch = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutThemeSwitch.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayoutThemeSwitch.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutThemeSwitch.setObjectName("horizontalLayoutThemeSwitch")
        self.radioButtonDarkTheme = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButtonDarkTheme.setChecked(False)
        self.radioButtonDarkTheme.setObjectName("radioButtonDarkTheme")
        self.horizontalLayoutThemeSwitch.addWidget(self.radioButtonDarkTheme)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupBoxThemeSwitch)
        self.line = QtWidgets.QFrame(PreferencesDialog)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line)
        self.labelRegisterMapFile = QtWidgets.QLabel(PreferencesDialog)
        self.labelRegisterMapFile.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelRegisterMapFile.setFont(font)
        self.labelRegisterMapFile.setObjectName("labelRegisterMapFile")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRegisterMapFile)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditRegisterMapFile = QtWidgets.QLineEdit(PreferencesDialog)
        self.lineEditRegisterMapFile.setObjectName("lineEditRegisterMapFile")
        self.horizontalLayout_2.addWidget(self.lineEditRegisterMapFile)
        self.pushButtonSelectRegisterMapFile = QtWidgets.QPushButton(PreferencesDialog)
        self.pushButtonSelectRegisterMapFile.setObjectName("pushButtonSelectRegisterMapFile")
        self.horizontalLayout_2.addWidget(self.pushButtonSelectRegisterMapFile)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.labelRegConExecutable = QtWidgets.QLabel(PreferencesDialog)
        self.labelRegConExecutable.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelRegConExecutable.setFont(font)
        self.labelRegConExecutable.setObjectName("labelRegConExecutable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelRegConExecutable)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditRegConExecutablePath = QtWidgets.QLineEdit(PreferencesDialog)
        self.lineEditRegConExecutablePath.setToolTipDuration(5)
        self.lineEditRegConExecutablePath.setObjectName("lineEditRegConExecutablePath")
        self.horizontalLayout_3.addWidget(self.lineEditRegConExecutablePath)
        self.pushButtonSelectRegConExecutablePath = QtWidgets.QPushButton(PreferencesDialog)
        self.pushButtonSelectRegConExecutablePath.setObjectName("pushButtonSelectRegConExecutablePath")
        self.horizontalLayout_3.addWidget(self.pushButtonSelectRegConExecutablePath)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.labelBehaviour = QtWidgets.QLabel(PreferencesDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelBehaviour.setFont(font)
        self.labelBehaviour.setObjectName("labelBehaviour")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelBehaviour)
        self.radioButtonConvertRegisterMapOnStartup = QtWidgets.QRadioButton(PreferencesDialog)
        self.radioButtonConvertRegisterMapOnStartup.setChecked(True)
        self.radioButtonConvertRegisterMapOnStartup.setObjectName("radioButtonConvertRegisterMapOnStartup")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButtonConvertRegisterMapOnStartup)
        self.line_2 = QtWidgets.QFrame(PreferencesDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line_2)
        self.labelRegisterAccessPath = QtWidgets.QLabel(PreferencesDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelRegisterAccessPath.setFont(font)
        self.labelRegisterAccessPath.setObjectName("labelRegisterAccessPath")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelRegisterAccessPath)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditRegisterAccessPath = QtWidgets.QLineEdit(PreferencesDialog)
        self.lineEditRegisterAccessPath.setToolTipDuration(5)
        self.lineEditRegisterAccessPath.setObjectName("lineEditRegisterAccessPath")
        self.horizontalLayout_4.addWidget(self.lineEditRegisterAccessPath)
        self.pushButtonSelectRegisterAccessPath = QtWidgets.QPushButton(PreferencesDialog)
        self.pushButtonSelectRegisterAccessPath.setObjectName("pushButtonSelectRegisterAccessPath")
        self.horizontalLayout_4.addWidget(self.pushButtonSelectRegisterAccessPath)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.labelBoardCtrlPath = QtWidgets.QLabel(PreferencesDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelBoardCtrlPath.setFont(font)
        self.labelBoardCtrlPath.setObjectName("labelBoardCtrlPath")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelBoardCtrlPath)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditBoardControlPath = QtWidgets.QLineEdit(PreferencesDialog)
        self.lineEditBoardControlPath.setToolTipDuration(2)
        self.lineEditBoardControlPath.setObjectName("lineEditBoardControlPath")
        self.horizontalLayout_5.addWidget(self.lineEditBoardControlPath)
        self.pushButtonSelectBoardCtrlPath = QtWidgets.QPushButton(PreferencesDialog)
        self.pushButtonSelectBoardCtrlPath.setObjectName("pushButtonSelectBoardCtrlPath")
        self.horizontalLayout_5.addWidget(self.pushButtonSelectBoardCtrlPath)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.line_3 = QtWidgets.QFrame(PreferencesDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.line_3)
        self.labelAvailableBaudRates = QtWidgets.QLabel(PreferencesDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelAvailableBaudRates.setFont(font)
        self.labelAvailableBaudRates.setObjectName("labelAvailableBaudRates")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelAvailableBaudRates)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditAvailableBaudRates = QtWidgets.QLineEdit(PreferencesDialog)
        self.lineEditAvailableBaudRates.setToolTipDuration(5)
        self.lineEditAvailableBaudRates.setObjectName("lineEditAvailableBaudRates")
        self.verticalLayout_2.addWidget(self.lineEditAvailableBaudRates)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.labelDutScriptPath = QtWidgets.QLabel(PreferencesDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelDutScriptPath.setFont(font)
        self.labelDutScriptPath.setObjectName("labelDutScriptPath")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelDutScriptPath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditDutScriptPath = QtWidgets.QLineEdit(PreferencesDialog)
        self.lineEditDutScriptPath.setObjectName("lineEditDutScriptPath")
        self.horizontalLayout.addWidget(self.lineEditDutScriptPath)
        self.pushButtonSelectDutScriptPath = QtWidgets.QPushButton(PreferencesDialog)
        self.pushButtonSelectDutScriptPath.setObjectName("pushButtonSelectDutScriptPath")
        self.horizontalLayout.addWidget(self.pushButtonSelectDutScriptPath)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtWidgets.QApplication.translate("PreferencesDialog", "Dialog", None, -1))
        self.labelAppearance.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Appearance", None, -1))
        self.radioButtonDarkTheme.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Dark Theme", None, -1))
        self.labelRegisterMapFile.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Register Map File", None, -1))
        self.lineEditRegisterMapFile.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Register Map", None, -1))
        self.lineEditRegisterMapFile.setPlaceholderText(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Register Map", None, -1))
        self.pushButtonSelectRegisterMapFile.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Browse", None, -1))
        self.labelRegConExecutable.setText(QtWidgets.QApplication.translate("PreferencesDialog", "RegCon Executable Path", None, -1))
        self.lineEditRegConExecutablePath.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to RegCon Script", None, -1))
        self.lineEditRegConExecutablePath.setPlaceholderText(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to RegCon Script", None, -1))
        self.pushButtonSelectRegConExecutablePath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Browse", None, -1))
        self.labelBehaviour.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Behaviour", None, -1))
        self.radioButtonConvertRegisterMapOnStartup.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Convert Register Map on Startup", None, -1))
        self.labelRegisterAccessPath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Register Access Path", None, -1))
        self.lineEditRegisterAccessPath.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Register Access Script", None, -1))
        self.lineEditRegisterAccessPath.setPlaceholderText(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Register Access Script", None, -1))
        self.pushButtonSelectRegisterAccessPath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Browse", None, -1))
        self.labelBoardCtrlPath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Board Control Path", None, -1))
        self.lineEditBoardControlPath.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Board Control Script", None, -1))
        self.lineEditBoardControlPath.setPlaceholderText(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Board Control Script", None, -1))
        self.pushButtonSelectBoardCtrlPath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Browse", None, -1))
        self.labelAvailableBaudRates.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Available Baud Rates", None, -1))
        self.lineEditAvailableBaudRates.setToolTip(QtWidgets.QApplication.translate("PreferencesDialog", "Enter Baud Rates, seperated with \";\"", None, -1))
        self.lineEditAvailableBaudRates.setPlaceholderText(QtWidgets.QApplication.translate("PreferencesDialog", "Enter Baud Rates, seperated with \";\"", None, -1))
        self.labelDutScriptPath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "DUT Script Path", None, -1))
        self.lineEditDutScriptPath.setPlaceholderText(QtWidgets.QApplication.translate("PreferencesDialog", "Select Path to Dut Script", None, -1))
        self.pushButtonSelectDutScriptPath.setText(QtWidgets.QApplication.translate("PreferencesDialog", "Browse", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PreferencesDialog = QtWidgets.QDialog()
    ui = Ui_PreferencesDialog()
    ui.setupUi(PreferencesDialog)
    PreferencesDialog.show()
    sys.exit(app.exec_())

