# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'unote_gui.ui'
##
## Created by: Qt User Interface Compiler version 5.14.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1680, 1027)
        MainWindow.setToolTipDuration(5)
        MainWindow.setIconSize(QSize(64, 64))
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionExit.setCheckable(False)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionLoad_PDF = QAction(MainWindow)
        self.actionLoad_PDF.setObjectName(u"actionLoad_PDF")
        self.actionText_Mode = QAction(MainWindow)
        self.actionText_Mode.setObjectName(u"actionText_Mode")
        self.actionText_Mode.setCheckable(True)
        self.actionHighlight_Mode = QAction(MainWindow)
        self.actionHighlight_Mode.setObjectName(u"actionHighlight_Mode")
        self.actionHighlight_Mode.setCheckable(True)
        self.actionSave_PDF = QAction(MainWindow)
        self.actionSave_PDF.setObjectName(u"actionSave_PDF")
        self.actionPageInsertHere = QAction(MainWindow)
        self.actionPageInsertHere.setObjectName(u"actionPageInsertHere")
        self.actionExtract = QAction(MainWindow)
        self.actionExtract.setObjectName(u"actionExtract")
        self.actionPageDeleteActive = QAction(MainWindow)
        self.actionPageDeleteActive.setObjectName(u"actionPageDeleteActive")
        self.actionPageMoveUp = QAction(MainWindow)
        self.actionPageMoveUp.setObjectName(u"actionPageMoveUp")
        self.actionPageMoveDown = QAction(MainWindow)
        self.actionPageMoveDown.setObjectName(u"actionPageMoveDown")
        self.actionPageMoveTo_Page = QAction(MainWindow)
        self.actionPageMoveTo_Page.setObjectName(u"actionPageMoveTo_Page")
        self.actionHelpAbout = QAction(MainWindow)
        self.actionHelpAbout.setObjectName(u"actionHelpAbout")
        self.actionSave_PDF_as = QAction(MainWindow)
        self.actionSave_PDF_as.setObjectName(u"actionSave_PDF_as")
        self.actionNew_PDF = QAction(MainWindow)
        self.actionNew_PDF.setObjectName(u"actionNew_PDF")
        self.actionPageGoto = QAction(MainWindow)
        self.actionPageGoto.setObjectName(u"actionPageGoto")
        self.actionHelpDonate = QAction(MainWindow)
        self.actionHelpDonate.setObjectName(u"actionHelpDonate")
        self.actionHelpCheck_for_Updates = QAction(MainWindow)
        self.actionHelpCheck_for_Updates.setObjectName(u"actionHelpCheck_for_Updates")
        self.actionZoomToFit = QAction(MainWindow)
        self.actionZoomToFit.setObjectName(u"actionZoomToFit")
        self.actionZoomIn = QAction(MainWindow)
        self.actionZoomIn.setObjectName(u"actionZoomIn")
        self.actionZoomOut = QAction(MainWindow)
        self.actionZoomOut.setObjectName(u"actionZoomOut")
        self.actionPageSplitView = QAction(MainWindow)
        self.actionPageSplitView.setObjectName(u"actionPageSplitView")
        self.actionPageSplitView.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_6 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")

        self.verticalLayout_6.addLayout(self.gridLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1680, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuPage = QMenu(self.menubar)
        self.menuPage.setObjectName(u"menuPage")
        self.menuPageMove = QMenu(self.menuPage)
        self.menuPageMove.setObjectName(u"menuPageMove")
        self.menuZoom = QMenu(self.menuPage)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPage.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_PDF)
        self.menuFile.addAction(self.actionLoad_PDF)
        self.menuFile.addAction(self.actionSave_PDF)
        self.menuFile.addAction(self.actionSave_PDF_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPage.addAction(self.actionPageInsertHere)
        self.menuPage.addAction(self.actionPageDeleteActive)
        self.menuPage.addAction(self.menuPageMove.menuAction())
        self.menuPage.addSeparator()
        self.menuPage.addAction(self.actionPageGoto)
        self.menuPage.addSeparator()
        self.menuPage.addAction(self.menuZoom.menuAction())
        self.menuPage.addSeparator()
        self.menuPage.addAction(self.actionPageSplitView)
        self.menuPageMove.addAction(self.actionPageMoveUp)
        self.menuPageMove.addAction(self.actionPageMoveDown)
        self.menuPageMove.addAction(self.actionPageMoveTo_Page)
        self.menuZoom.addAction(self.actionZoomToFit)
        self.menuZoom.addSeparator()
        self.menuZoom.addAction(self.actionZoomIn)
        self.menuZoom.addAction(self.actionZoomOut)
        self.menuHelp.addAction(self.actionHelpCheck_for_Updates)
        self.menuHelp.addAction(self.actionHelpAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelpDonate)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"UNote", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad_PDF.setText(QCoreApplication.translate("MainWindow", u"Load PDF", None))
#if QT_CONFIG(shortcut)
        self.actionLoad_PDF.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionText_Mode.setText(QCoreApplication.translate("MainWindow", u"Text Mode", None))
#if QT_CONFIG(shortcut)
        self.actionText_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionHighlight_Mode.setText(QCoreApplication.translate("MainWindow", u"Highlight Mode", None))
#if QT_CONFIG(shortcut)
        self.actionHighlight_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_PDF.setText(QCoreApplication.translate("MainWindow", u"Save PDF", None))
#if QT_CONFIG(shortcut)
        self.actionSave_PDF.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPageInsertHere.setText(QCoreApplication.translate("MainWindow", u"Insert Here", None))
#if QT_CONFIG(shortcut)
        self.actionPageInsertHere.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExtract.setText(QCoreApplication.translate("MainWindow", u"Extract", None))
        self.actionPageDeleteActive.setText(QCoreApplication.translate("MainWindow", u"Delete Active", None))
        self.actionPageMoveUp.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.actionPageMoveDown.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.actionPageMoveTo_Page.setText(QCoreApplication.translate("MainWindow", u"To Page", None))
        self.actionHelpAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionSave_PDF_as.setText(QCoreApplication.translate("MainWindow", u"Save PDF as", None))
#if QT_CONFIG(shortcut)
        self.actionSave_PDF_as.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_PDF.setText(QCoreApplication.translate("MainWindow", u"New PDF", None))
#if QT_CONFIG(shortcut)
        self.actionNew_PDF.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionPageGoto.setText(QCoreApplication.translate("MainWindow", u"Goto", None))
#if QT_CONFIG(shortcut)
        self.actionPageGoto.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelpDonate.setText(QCoreApplication.translate("MainWindow", u"Support the DevOp", None))
        self.actionHelpCheck_for_Updates.setText(QCoreApplication.translate("MainWindow", u"Check for Updates", None))
        self.actionZoomToFit.setText(QCoreApplication.translate("MainWindow", u"To Fit", None))
#if QT_CONFIG(shortcut)
        self.actionZoomToFit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+\\", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomIn.setText(QCoreApplication.translate("MainWindow", u"In", None))
#if QT_CONFIG(shortcut)
        self.actionZoomIn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+]", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomOut.setText(QCoreApplication.translate("MainWindow", u"Out", None))
#if QT_CONFIG(shortcut)
        self.actionZoomOut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionPageSplitView.setText(QCoreApplication.translate("MainWindow", u"Split View", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuPage.setTitle(QCoreApplication.translate("MainWindow", u"Page", None))
        self.menuPageMove.setTitle(QCoreApplication.translate("MainWindow", u"Move Active", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

