# ---------------------------------------------------------------
# -- UNote Main File --
#
# Main File for running the UNote
#
# Author: Melvin Strobl
# ---------------------------------------------------------------


# ----------------------------------------------------------
# Import region
# ----------------------------------------------------------
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import pyqtSignal, QFile, QTextStream, pyqtSlot, QObject
from PyQt5.QtWidgets import QDialog, QGraphicsView, QGraphicsScene, QWidget

from fbs_runtime.application_context.PyQt5 import ApplicationContext

import argparse  # parsing cmdline arguments
import os  # launching external python script
import sys  # exit script, file parsing
import subprocess  # for running external cmds
import atexit


# app = QApplication(sys.argv)
# file = QFile(":/dark.qss")
# file.open(QFile.ReadOnly | QFile.Text)
# stream = QTextStream(file)
# app.setStyleSheet(stream.readAll())

SCRIPTDIR = os.path.dirname(os.path.realpath(__file__))

sys.path.append('./ui')

from ui import Ui_MainWindow

from unote_receivers import Receivers
from preferences_gui import PreferencesGUI
from preferences import Preferences
from core import GraphicsViewHandler
from toolbox import ToolBoxWidget

TOOLBOXWIDTH = 200
TOOLBOXHEIGHT = 200
TOOLBOXSTARTX = 200
TOOLBOXSTARTY = 200

MAINWINDOWSTARTX = 0
MAINWINDOWSTARTY = 0
MAINWINDOWWIDTH = 1920
MAINWINDOWHEIGHT = 1080

class UNote():
    '''
    Main class for the UNote
    '''

    def __init__(self, pdfLoad):
        super().__init__()


        self.initUI()

        t = QtCore.QTimer()
        t.singleShot(0, self.onQApplicationStarted)



        self.preferencesGui = PreferencesGUI()

        self.receiversInst = Receivers(self.ui)

        self.connectReceivers()

        if pdfLoad:
            self.ui.graphicsView.loadPdfToCurrentView(os.path.abspath(pdfLoad))


    def initUI(self):
        '''
        Initialize mandatory ui components
        '''
        # Create an application context
        # self.app = QtWidgets.QApplication(sys.argv)
        self.appctxt = ApplicationContext()

        self.MainWindow = QtWidgets.QMainWindow()

        self.ui = Ui_MainWindow()

        # Load the ui definitions generated by qt designer
        self.ui.setupUi(self.MainWindow)

        # Load the icon
        self.MainWindow.setWindowIcon(QtGui.QIcon("./assets/icon.png"))

        # Initialize graphicviewhandler. This is a core component of unote
        self.ui.graphicsView = GraphicsViewHandler(self.ui.centralwidget)
        # Simply use the whole window
        self.ui.gridLayout.addWidget(self.ui.graphicsView, 0, 0, 1, 1)

        # Initialize a floating toolboxwidget. This is used for storing tools and editing texts
        self.ui.floatingToolBox = ToolBoxWidget(self.MainWindow)
        self.ui.floatingToolBox.setWindowFlags(QtCore.Qt.WindowTitleHint | QtCore.Qt.FramelessWindowHint)
        self.ui.floatingToolBox.setObjectName("floatingToolBox")
        self.ui.floatingToolBox.setGeometry(QtCore.QRect(TOOLBOXSTARTX, TOOLBOXSTARTY, TOOLBOXWIDTH, TOOLBOXHEIGHT))
        self.ui.floatingToolBox.show()
        # self.ui.floatingToolBox.setStyleSheet("background-color:black")


    def run(self, args):
        '''
        Starts the UNote
        '''
        self.MainWindow.show()

        result = self.appctxt.app.exec_()

        self.onQApplicationQuit()

        sys.exit(result)

    def onQApplicationStarted(self):
        '''
        Executed immediately when Application started
        '''
        #Update window sizes
        try:
            # Use local preferences to restore window sizes
            self.MainWindow.setGeometry(int(Preferences.data['windowXPos']), int(Preferences.data['windowYPos']), int(Preferences.data['windowWidth']), int(Preferences.data['windowHeight']))
        except Exception as identifier:
            print("Unable to restore window size: " + str(identifier))

            # Try to use default geometry if that fails
            try:
                self.MainWindow.setGeometry(MAINWINDOWSTARTX, MAINWINDOWSTARTY, MAINWINDOWWIDTH, MAINWINDOWHEIGHT)
            except:
                print("Even unable to restore default window size. Is there even a monitor attached?")

    def onQApplicationQuit(self):
        '''
        Executed immediately when Application stops
        '''
        Preferences.updateKeyValue('windowHeight', self.MainWindow.height())
        Preferences.updateKeyValue('windowWidth', self.MainWindow.width())
        Preferences.updateKeyValue('windowXPos', self.MainWindow.x())
        Preferences.updateKeyValue('windowYPos', self.MainWindow.y())

        self.preferencesGui.storeSettings()



    def connectReceivers(self):
        '''
        Connects all the buttons to the right receivers
        '''
        # Add the exit method
        self.ui.actionExit.triggered.connect(self.appctxt.app.quit)

        # Open Preferences
        self.ui.actionPreferences.triggered.connect(lambda:self.receiversInst.openPreferencesReceiver(self.preferencesGui))

        # Load PDF File
        self.ui.actionLoad_PDF.triggered.connect(lambda:self.receiversInst.loadPdf())

        # Save PDF
        self.ui.actionSave_PDF.triggered.connect(lambda:self.receiversInst.savePdf())

        # Save PDF as
        self.ui.actionSave_PDF_as.triggered.connect(lambda:self.receiversInst.savePdfAs())

        # Insert PDF Page
        self.ui.actionPageInsertHere.triggered.connect(lambda:self.receiversInst.pageInsertHere())

        # Delete Active PDF Page
        self.ui.actionPageInsertHere.triggered.connect(lambda:self.receiversInst.pageDeleteActive())

        # Toolbox Edit modes available
        self.ui.floatingToolBox.editModeChange.connect(self.ui.graphicsView.editModeChangeRequest)

        # Toolboxspecific events
        self.ui.floatingToolBox.textInputFinished.connect(self.ui.graphicsView.toolBoxTextInputEvent)
        self.ui.graphicsView.requestTextInput.connect(self.ui.floatingToolBox.handleTextInputRequest)

# ----------------------------------------------------------
# User Parameter region
# ----------------------------------------------------------


# ----------------------------------------------------------
# Variable region
# ----------------------------------------------------------


# ----------------------------------------------------------
# Helper Fct for handling input arguments
# ----------------------------------------------------------
def argumentHelper():
    '''
    Just a helper for processing the arguments
    '''

    # Define Help Te
    helpText = 'Register Converter Script'
    # Create ArgumentParser instance
    argparser = argparse.ArgumentParser(description=helpText)

    argparser.add_argument('-p', '--pdf',
                        help='Load pdf')

    return argparser.parse_args()


# ----------------------------------------------------------
# Called on script exit
# ----------------------------------------------------------
def exitMethod():
    '''
    Called for exiting the program
    '''

    sys.exit("\n\nExiting UNote\n")


# ----------------------------------------------------------
# Main Entry Point
# ----------------------------------------------------------
def main():
    '''
    Main method handling the flow
    '''

    # -----------------------------------------------------
    # -----------------At Exit Register------------------
    atexit.register(exitMethod)

    # -----------------------------------------------------
    # ---------------Argument processing------------------
    args = None
    try:
        args = argumentHelper()
    except ValueError as e:
        sys.exit("Unable to parse arguments:\n" + str(e))

    UNoteGUI = UNote(args.pdf)
    UNoteGUI.run(args)


# Standard python script entry handling
if __name__ == '__main__':
    main()
